# pull the official base image
FROM node:latest
# set working direction
WORKDIR /app
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
# install application dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install
# add app
COPY . ./
ENV NODE_OPTIONS=--openssl-legacy-provider
EXPOSE 3000
# start app
CMD ["npm", "start"]