version: "3.9"
   
services:
  db:
    container_name: postgres
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ..a/2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
  api:
    container_name: api
    build: 
      context: ./backend/
    ports:
      - "5000:80"
    depends_on:
      - db
  web:
    container_name: client
    build: 
      context: ./frontend/
    volumes:
      - './:/frontend'
      - '/frontend/node_modules'
    ports:
      - "3000:3000"
    depends_on:
      - api
